name: ds_tutorial
dependencies:
 - pandas
#  - numpy
#  - matplotlib
#  - scikit-learn
#  - seaborn
#  - jupyter
#  - pandas-datareader
#  - pillow
#  - cython
#  # - cudnn
#  - opencv
#  - lxml
#  - beautifulsoup4
#  - pip
#  - tensorflow
#  - keras
#  - tqdm
#  - xgboost
#  - lightgbm
#  - spacy
