[tool.poetry]
name = "ds_tutorial"
version = "0.0.1"
description = "Little bit datascience stuff"
authors = ["Jochen Wersdörfer <jochen@wersdoerfer.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ephes/data_science_tutorial"
keywords = [
    "data science", "keras", "classification", "clustering", "tutorial"
]
classifiers = [
    "Development Status :: 3 - Alpha",
]
packages = [
    { include = "./commands.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
scikit-learn = "*"
jupyter = "^1"
tensorflow = "^2"
tqdm = "^4"
xgboost = "^1"
pandas = "^1"
dask = {extras = ["complete"], version = "^2"}
distributed = "^2"
typer = "*"
s3fs = "*"
matplotlib = "^3.3.3"
Keras = "^2.4.3"

[tool.poetry.scripts]
test = "commands:pytest"
lint = "commands:flake8"
autoformat = "commands:black"
show_coverage = "commands:coverage"
docs = "commands:docs"
notebook = "commands:notebook"
clean-pyc = "commands:clean_pyc"
clean = "commands:clean"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

