# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data_science_tutorial',
                'doc_host': 'https://ephes.github.io',
                'git_url': 'https://github.com/ephes/data_science_tutorial',
                'lib_path': 'data_science_tutorial'},
  'syms': {'data_science_tutorial.core': {'data_science_tutorial.core.foo': ('core.html#foo', 'data_science_tutorial/core.py')}}}
