# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data_science_tutorial',
                'doc_host': 'https://ephes.github.io',
                'git_url': 'https://github.com/ephes/data_science_tutorial',
                'lib_path': 'ds_tut'},
  'syms': { 'ds_tut.core': {'ds_tut.core.foo': ('core.html#foo', 'ds_tut/core.py')},
            'ds_tut.ds_tut': {'ds_tut.ds_tut.foo': ('core.html#foo', 'ds_tut/ds_tut.py')},
            'ds_tut.io': {'ds_tut.io.download_from_url': ('io.html#download_from_url', 'ds_tut/io.py')}}}
